import random
import os
import re
import csv
from typing import List, Dict


def build_refactoring_prompt(
    sample_id: int,
    refactoring_type: str,
    feature_pool: List[str],
    max_feature_cnt: int = 6
) -> Dict:
    pick_num = random.randint(1, max_feature_cnt)
    picked_features = random.sample(feature_pool, k=pick_num)

    source_cls = f"SourceClass{sample_id}"
    target_cls = f"TargetClass{sample_id}"

    description = f"""Task: Generate a complete, compilable Java program for refactoring engine testing. The target refactoring operation is: {refactoring_type}. Output only the Java source code with no extra text, descriptions or explanations. The generated Java program must satisfy all requirements in the Conditions and Features sections. Do not introduce any redundant logic beyond the required features."""

    conditions = f"""[Conditions]
    1. Source class name: {source_cls}
    2. the method name of the statement to be extracted: refMethod
    3. mark the statement for extracting local variables that need to be executed with special symbols:/*EXTRACT*/
    4. The package name: test.extractmethod """

    feature_text_lines = "\n".join([f"- {ft}" for ft in picked_features])
    features = f"""[Features]
{feature_text_lines}"""

    full_prompt = f"""===== PROMPT SAMPLE {sample_id} =====
[Description]
{description}

{conditions}

{features}"""

    return {
        "sample_id": sample_id,
        "refactoring_type": refactoring_type,
        "pick_feature_count": pick_num,
        "source_class": source_cls,
        "target_class": target_cls,
        "picked_features": picked_features,
        "Description": description,
        "Conditions": conditions,
        "Features": features,
        "full_prompt": full_prompt
    }


def batch_generate_prompts(
    total_generate: int,
    refactoring_type: str,
    feature_pool: List[str],
    max_feature: int = 6
) -> List[Dict]:
    result_list = []
    for sid in range(1, total_generate + 1):
        item = build_refactoring_prompt(
            sample_id=sid,
            refactoring_type=refactoring_type,
            feature_pool=feature_pool,
            max_feature_cnt=max_feature
        )
        result_list.append(item)
    return result_list


def extract_java_code(llm_response_text: str) -> str:
    pattern = re.compile(r"```java\s*(.*?)```", re.DOTALL)
    match = pattern.search(llm_response_text)
    if match:
        code = match.group(1)
    else:
        code = llm_response_text
    return code.strip()


def save_java_file(sample_id: int, llm_response_text: str, output_root_dir: str = "./gen_java_output"):
    os.makedirs(output_root_dir, exist_ok=True)
    java_code = extract_java_code(llm_response_text)
    filename = f"SourceClass{sample_id}.java"
    full_path = os.path.join(output_root_dir, filename)

    with open(full_path, "w", encoding="utf-8") as f:
        f.write(java_code)
    print(f"✅ 已保存：{full_path}")
    return full_path

if __name__ == "__main__":
    extract_method_features = [
    "Method declares reference type parameter and contains boolean expression invoking member on this parameter.",
    "Boolean expression is selected as extraction target for Extract Method.",
    "Class defines static method returning generic Pair and accepting two string parameters.",
    "Main method declares generic collection variable and string local variable.",
    "Two consecutive lines invoke static method and add returned value into collection.",
    "First static invocation uses only string literals; second mixes string literal and defined local variable.",
    "Method contains nested try blocks with layered exception handling.",
    "Inner try block includes finally clause executing regardless of return statement.",
    "Catch block handles specific exceptions to improve error resilience.",
    "Finally block guarantees execution for cleanup or logging purposes.",
    "Outer try structure provides extra exception handling beyond inner block scope.",
    "Return statement exists inside inner try block and affects control flow order.",
    "Model class contains private field and constructor.",
    "Static method in main class accepts string parameter and declares reference local variable.",
    "Method body has two sequential if conditional branches, each assigns local variable and returns.",
    "Default assignment and final return statement exist after if branches.",
    "Class defines void method with single method call statement inside method body.",
    "Argument of method call is chained string concatenation expression composed of multiple string literals.",
    "Class defines method returning generic Map type.",
    "Two other methods invoke this generic Map method; one calls get on returned map, another calls keySet.",
    "Generic Map method invocation is part of an expression inside one method.",
    "Method declares and initializes three integer local variables.",
    "Return statement returns boolean expression chained by && operators.",
    "Full boolean expression consists of literal true, a < b and b <= c joined by short-circuit AND.",
    "Generic method declares type parameter <T> and returns Class<T>.",
    "Static method is invoked inside method body; its last argument is ternary expression to get class loader.",
    "Both branches of ternary expression return class loader and do not rely on generic type parameter T.",
    "Outer class contains static inner class.",
    "Static inner class defines instance boolean field.",
    "Instance method inside static inner class has two consecutive assignment statements to instance field.",
    "Method contains infinite while loop statement.",
    "Loop body contains if conditional branch with continue statement; field assignment after if branch.",
    "Selected target is all statements inside the while loop body.",
    "Method contains outer try-catch statement whose catch clause catches Error.",
    "Outer try block contains nested complete try-finally block with return statement in try body and statements in finally block.",
    "Selected target is the entire nested try-finally block.",
    "Method contains outer try-catch statement with catch clause catching Error.",
    "Outer try block contains nested complete try-finally block; nested try block has return expression, finally block contains print statement.",
    "Selected target is the entire nested try-finally block.",
    "Class declares private reference type field.",
    "Inside method, field is accessed twice: one assignment to Object variable, another chained member access on the field.",
    "Nested static inner class structure exists in the class.",
    "Class contains two boolean methods.",
    "First method returns chained boolean expression joined by && checking instanceof against specific interface type.",
    "Second method returns chained boolean expression with identical structure, only the type in instanceof check differs.",
    "Both expressions use same variable names; syntactic structure same but checked types in instanceof differ.",
    "Method declares integer local variable and generic collection variable.",
    "There is a for loop statement, and a reference local variable is declared inside loop.",
    "Loop body has if branch constructing new array, invoking array copy methods, modifying array variable and loop index variable, executing continue.",
    "After loop, there is if condition check, collection method invocation and return statement.",
    "Variable 'file' is declared only inside loop block and local to loop.",
    "Method returns reference type and contains enhanced for-each loop.",
    "For-each loop declares loop variable; inside loop if branch returns loop variable when condition matches.",
    "After loop, return statement returns null.",
    "Class declares two collection instance fields.",
    "Two void methods have identical source code: two collection add invocations separated by single-line comment.",
    "Statements and comment inside method1 and method2 are exactly the same.",
    "Outer class contains static generic inner class declaring type parameter <E extends Throwable>.",
    "Instance method inside static inner class has throws clause referencing generic type E.",
    "Method b of outer class constructs inner class instance parameterized with RuntimeException and invokes method a.",
    "Method declares local Object variable with final modifier.",
    "Method body contains Thread constructor invocation; argument of Thread constructor is anonymous Runnable inner class instance.",
    "run method inside anonymous Runnable accesses the final local variable from outer method.",
    "Extract code containing if statement.",
    "Extract code containing method calls.",
    "The extraction code contains judgment statements.",
    "Method declares array local variable and initializes array instance.",
    "Assignment is performed on index 0 of array.",
    "Subsequent statement uses array variable as argument of method call.",
    "Selected target includes array declaration statement and array element assignment statement.",
    "Class defines instance integer field myValue.",
    "Class constructor reads this field as argument of method call.",
    "init instance method performs write assignment to this field.",
    "Selected target is field read expression inside constructor.",
    "Class A in package a defines static constant FOO.",
    "Class B in package b imports static members from A via import static a.A.*.",
    "Method test inside B uses simple name FOO as part of string concatenation expression.",
    "Class defines two instance fields.",
    "Class has constructor with two parameters; constructor body contains two field assignment statements.",
    "Selected target is one field assignment statement inside constructor.",
    "Class defines instance method with varargs parameter Object... array.",
    "Inside method body, Object local variable is declared and assigned null.",
    "Last line of method body is expression calling equals on varargs variable, using local variable as argument.",
    "Selected target is the last method call expression.",
    "Method declares string local variable o with initialization.",
    "Selected code block contains declaration of string variable s, complete try-finally statement and return statement; variable s is declared inside selected block.",
    "Class defines generic method method with type parameter <T>, returns Collection<T> and accepts Class<T> argument.",
    "Another generic method testMethod declares <T>; inside it invokes method(clazz), assigning result to Collection<T> variable.",
    "Selected target is method(clazz) invocation expression.",
    "Method has two separate for loop blocks.",
    "First for loop condition i < 10, loop body prints string literal \"foo\".",
    "Second for loop condition i < 10, loop body prints string literal \"bar\".",
    "Two loops have identical AST structure, only value of string literal differs.",
    "Method accepts a varargs parameter of type Object, allowing any number of Object arguments.",
    "Inside method, local Object variable is initialized to null.",
    "Method performs equality check using equals() comparing array parameter to local object variable.",
    "array.equals(object) compares array itself and null object and may cause unexpected behavior.",
    "Method does not return any value or perform further logic beyond equality check.",
    "Method declares two integer local variables.",
    "Method body contains outer if-else statement; outer if contains nested if with return; outer else branch also has return.",
    "Selected target is composite if statement block starting from outer if and ending with return; multiple return exit points exist inside selected block.",
    "One print statement remains after selected block.",
    "Class defines two separate methods.",
    "Extract code containing method calls.",
    "Two methods contain the same method body.",
    "The extracted statement is an assignment expression.",
    "Instance method keyTyped accepts KeyEvent parameter.",
    "Method body declares final local variable, contains if branch with return, print statement, method calls, if block with multiple UI component operation statements.",
    "Selected target is all statements inside the method braces.",
    "An if statement checks a certain condition.",
    "If condition is met, continue statement skips rest of current iteration and proceeds to next loop iteration.",
    "If condition is not met, additional code is executed.",
    "Method contains for loop statement.",
    "Inside for loop body are multiple lines of code; selected fragment inside loop body includes if condition branch with continue statement.",
    "continue targets outer for loop scope.",
    "Class A declares private instance field o.",
    "Inside method foo: local variable m is assigned from field o; call method receives arguments m and this.o.",
    "m, o and this.o are aliases referring to same field.",
    "Selected target is field access expression this.o.",
    "Subclass ExtractMethodDemo extends SuperClass; subclass already has private method subMethod() returning String.",
    "SuperClass contains method someMethod(); method body has return statement returning string literal.",
    "Selected target is return statement fragment inside someMethod() of SuperClass.",
    "Method demonstrates string manipulation within a class.",
    "It includes a null check to handle potential null input, replacing it with empty string.",
    "String is trimmed of whitespace and converted to lowercase.",
    "Processed string is printed to console.",
    "Code suggests refactoring to extract string manipulation logic into utility class.",
    "Method annotated with @SuppressWarnings to suppress unchecked and raw type warnings.",
    "Method accepts List parameter for collection of items.",
    "Inside method, empty string is added to provided list.",
    "Method implementation may be part of generic codebase with type safety issues.",
    "Extract code containing if statement.",
    "Extract code containing while statement.",
    "Extract code containing break statement.",
    "Method accepts integer parameter and returns integer value.",
    "Conditional check determines if parameter exceeds a certain threshold.",
    "If condition is true, specific value is returned.",
    "If condition is false, message related to parameter is printed.",
    "Method returns original parameter if condition is not met.",
    "Marked section indicates potential refactoring or clarification area.",
    "Integer variable initialized with positive value.",
    "Loop continues as long as variable is greater than zero.",
    "Inside loop, conditional check for same variable.",
    "If condition is true, loop exits prematurely using break statement.",
    "Additional integer variable declared and initialized within loop.",
    "Loop control variable is updated with value of newly declared variable.",
    "Structure suggests potential logical issue as exit condition may never be met.",
    "Class defined as placeholder or data type.",
    "Method contains loop assigning value to variable while checking for null.",
    "Loop continues until assigned value is no longer null; potential infinite loop if method always returns null.",
    "Once non-null value obtained, separate method is called with that value.",
    "Value provider method always returns null and prevents loop termination.",
    "Method does not reference any instance members.",
    "Method performs task independent of object state.",
    "Method can be made static, independent of object instances.",
    "Automatically marking method as static improves clarity and removes unnecessary object references.",
    "Static method can be used without creating object instance.",
    "Class defines two separate methods.",
    "Methods have similar or identical logic.",
    "One method prepares or transforms input for the other method.",
    "Extracted expression is assignment or transformation of data.",
    "Extraction improves code reuse and modularity.",
    "Extracted method focuses on specific task such as parsing or transforming.",
    "Code fragment produces multiple output local variables including boolean variables hasAnyNullParam, hasAllNullParam and array variable bv.",
    "Extract Method in IDEA 8 creates wrapper inner class MapBindVariables to hold multiple return values.",
    "Wrapper class has constructor, invoke() method returning itself.",
    "Boolean fields in wrapper class generate JavaBean isXxx() accessors; non-boolean field generates getXxx() accessor.",
    "Outer class X contains anonymous Runnable inner class instance field.",
    "run method inside anonymous Runnable contains System.out.println(\"hello\"); statement.",
    "Java 16+ permits static methods inside non-static inner classes and anonymous classes.",
    "Selected target is println statement inside run method.",
    "Class Main has final instance field provider initialized in constructor.",
    "Inside setSomething: local variable foo is initialized by provider.getFoo(key); later foo is reassigned with provider.createDefaultFoo().",
    "Selected target is variable declaration statement Foo foo = provider.getFoo(key);",
    "Class DummyClass has instance field str1 with getter and setter.",
    "Method extraStr1 assigns local variable output using Java string template expression STR.\"ABC \\{str1}\".",
    "Selected target is string template expression STR.\"ABC \\{str1}\".",
    "Outer class extends component base class with private instance method; method declares local color variable assigned constant and invokes instance method to set background.",
    "Member inner class inside outer class also extends component base class; instance method of inner class has code fragment with identical AST and text.",
    "Selected target is full body of the instance method in outer class.",
    "Code has cast expression with generic type parameters, casting object to generic container type.",
    "Cast result invokes iteration method with anonymous procedure implementation.",
    "Selected target is the full expression containing generic cast.",
    "Original interface Bar<T, U> has two type parameters and two methods.",
    "Class Foo method accepts Bar<String, Integer> and invokes first method.",
    "Selected target is first method in interface; run Extract Interface to create SuperBar<T> with only this method.",
    "Bar becomes subtype of SuperBar<T>.",
    "Outer method has parameter; local class defined inside outer method.",
    "Instance method of local class creates lambda expression.",
    "Lambda captures outer method parameter and prints it.",
    "Selected target is code fragment inside lambda; extract method destination set to the local class.",
    "Variable is accessible in scope of new method and does not need to be passed as parameter.",
    "Same method is called multiple times in sequence.",
    "Called method takes constant value as argument.",
    "Repeated calls do not change argument passed to method.",
    "Method calls are identical in structure with no variation in parameters or logic.",
    "Repetitive method calls indicate potential refactoring to consolidate calls or abstract logic.",
    "Static method receives PsiMethod argument; inside retrieves test name, containing class, previous sibling method and iterates all methods of the class.",
    "Selected fragment is composite block inside loop body, including list variable initialization, null/empty check, file path construction and return statement.",
    "Selected fragment references two outer variables: testName (local variable from outer scope), psiMethod (loop variable).",
    "Extract code containing class if conditional statement.",
    "Extract code containing return statement.",
    "Method contains try-catch block to handle potential exceptions.",
    "In try block, operation creates annotation from text representation.",
    "If exception occurs, catch block handles it by returning default null value.",
    "Exception type caught is IncorrectOperationException.",
    "Method creates element from textual representation within specific project context.",
    "Java 8 interface default method test receives generic List<T> items.",
    "Inside it calls cache get with lambda as second argument.",
    "Lambda body constructs BitSet, loops over items, sets bits and returns result; code references captured variable items.",
    "Selected target is full code block inside lambda from BitSet creation to return result.",
    "Multi-way selection statement containing branch control structure.",
    "Specific branches of multi-way selection embed conditional logic.",
    "Execution of conditional branch ensures flow control through exit statement.",
    "Anonymous inner class is created within a method for on-the-fly class definition.",
    "Each anonymous class contains method returning integer value.",
    "Method does not store references to created objects and objects are immediately discarded.",
    "Lack of comments explaining purpose of anonymous classes.",
    "Same method name used in both anonymous classes suggesting redundancy.",
    "Structure demonstrates pattern for quick one-off interface implementations.",
    "Code does not operate on return values from anonymous class methods, potential oversight.",
    "Extract code containing class declaration statement.",
    "Extract code containing lambda expression.",
    "Extract code containing inner class.",
    "Static method receives three arguments: list, color object and string builder.",
    "forEach is called with statement lambda; lambda uses lambda parameter shape and captures outer scope variables newColor and stringBuilder.",
    "Selected target is two lines of code inside lambda body.",
    "Code defines lambda expression implementing FileFilter interface.",
    "Lambda takes File object as input.",
    "Lambda returns boolean value based on whether file name ends with .java extension.",
    "Filter condition uses endsWith() method on file's name.",
    "Extract code containing if statements.",
    "Extract code containing method calls.",
    "Extract code containing array creation.",
    "Method processes collection of objects for batch operations on graphical elements.",
    "Lambda expression used for iteration showing functional programming techniques.",
    "Mutable string builder used for efficient string concatenation with performance consideration.",
    "Method modifies state of each object, introducing side effects.",
    "Extract code containing if statements.",
    "Extract code containing method calls.",
    "Extract code containing array creation.",
    "Method should be accessible from other classes.",
    "Method should be callable directly using class name.",
    "Method should accept three parameters of specified types.",
    "Method should iterate over collection using a loop.",
    "Method should perform operations on each item during iteration.",
    "Method should append string representation of each item to provided string builder.",
    "Method should modify a property of each item.",
    "Method name should clearly indicate purpose: change item property and generate string of previous states.",
    "Method defines local anonymous class inside method.",
    "Anonymous class implements interface such as Runnable.",
    "Inside method, anonymous class references method in outer class.",
    "Anonymous class instantiated and used within same method scope.",
    "First method calls method on anonymous object such as getClass().",
    "Second method directly invokes run() method of anonymous class instance.",
    "Class defines method accepting functional interface as parameter.",
    "Method invoked inside functional interface throws checked exception.",
    "Try-catch block inside calling method handles exception.",
    "Exception is caught and ignored with no further action.",
    "Functional interface implemented by lambda expression invoking exception-throwing method.",
    "Code assigns value from method call to variable.",
    "Method call retrieves value based on two parameters, one being current index incremented by one.",
    "Variable is double type holding floating-point value.",
    "Comment indicates there is an issue to fix for this line.",
    "Method getValue() belongs to object or class referenced by solution.",
    "Second parameter of method call is constant 0, likely index or identifier.",
    "Code iterates over collection of objects.",
    "Collection retrieved from method of specific object.",
    "Each element in collection referenced within loop.",
    "Iteration uses enhanced for loop.",
    "Ellipsis indicates some logic executed for each element.",
    "Elements are objects possibly representing files or directories.",
    "Code defines method accepting class type as parameter.",
    "It retrieves all methods of given class using reflection.",
    "It filters methods based on return type, looking for return type assignable from Collection or Map.",
    "Filtering uses lambda expression inside filter method.",
    "Filtered results collected into list using collect method.",
    "Stream API is used for processing collection of methods.",
    "Class should be defined as public class allowing access from other classes.",
    "Class should contain method with no parameters and no return value.",
    "Method should utilize method reference referring to itself.",
    "Method should be defined within class and demonstrate Java 8 method reference.",
    "Method should be callable from instances of class.",
    "Method should be defined as private, restricting access to within its own class.",
    "Method should have no parameters and no return value.",
    "Method should contain conditional statement that immediately returns if condition is false.",
    "Method should include try block allowing exception handling.",
    "Method should have finally block executing after try block regardless of exception.",
    "Finally block should contain loop designed to run indefinitely.",
    "Loop should include break statement exiting loop immediately.",
    "Class should be defined within specific package.",
    "Class should contain integer instance variable initialized to specific value.",
    "Class should include public list holding objects of specified type.",
    "Method should have no parameters and no return value.",
    "Method should contain while loop continuing while specified condition is true.",
    "Method should retrieve object from list at specific index inside loop.",
    "Method should contain conditional statement breaking loop if retrieved object property exceeds threshold.",
    "Method should remove retrieved object from list if condition is not met.",
    "Method should perform calculation using property of retrieved object.",
    "Class should include nested static class with constructor initializing specific property.",
    "Method accepts several parameters including InputQuery<BedTrackData>, GenomeQuery, BINARIZATION, binSize, and list of Location objects.",
    "It first processes query with binarization method to generate list of Boolean values (bins).",
    "GenomeBins object created to handle binning logic for genomic data.",
    "Method iterates over list of locations for each location: retrieves chromosome and computes start and end offsets based on bin size.",
    "Counts how many bins in specified range are marked as true (positives).",
    "Compares count of positives to half total bins in range to decide whether location is enriched.",
    "Iteration results collected into list of Boolean values.",
    "Final result returned as list of Boolean indicating enrichment status for each location.",
    "Class should be defined within specific package.",
    "Class should contain integer instance variable initialized to specific value.",
    "Class should include public list holding objects of specified type.",
    "Method should have no parameters and no return value.",
    "The extraction code contains field access.",
    "Code assigns value from method call to variable.",
    "Method call retrieves value based on two parameters, one being current index incremented by one.",
    "The extraction code contains return statements.",
    "Extract code containing if statements.",
    "The extraction code contains for statements.",
    "Extract code containing array creation.",
    "Extract code containing if statements.",
    "The extraction code contains a try-catch block.",
    "Extract code containing method calls.",
    "Class should be defined within specific package.",
    "Class should contain main method serving as program entry point.",
    "Main method should define final variable initialized with string value.",
    "Main method should contain nested local class.",
    "Nested class should have public method returning string.",
    "Method in nested class should return value of final variable defined in main method.",
    "Main method creates instance of nested class, calls its method and prints result to console.",
    "Submit code appears multiple times in context.",
    "Extract code containing method calls.",
    "Extract code containing if statements.",
    "The extraction code contains for statements.",
    "Extract code containing array creation.",
    "Extract code containing method calls.",
    "Extract code containing list creation.",
    "Method accepts several parameters including InputQuery<BedTrackData>, GenomeQuery, BINARIZATION, binSize, and list of Location objects.",
    "It first processes query with binarization method to generate list of Boolean values (bins).",
    "GenomeBins object created to handle binning logic for genomic data.",
    "Method iterates over list of locations for each location: retrieves chromosome and computes start and end offsets based on bin size.",
    "Counts how many bins in specified range are marked as true (positives).",
    "Compares count of positives to half total bins in range to decide whether location is enriched.",
    "Iteration results collected into list of Boolean values.",
    "Final result returned as list of Boolean indicating enrichment status for each location.",
    "Class should define multiple overloaded methods with same name but different parameter types.",
    "First method should accept a list and two strings as parameters.",
    "Second method should accept a collection and two strings as parameters.",
    "Methods should not return any value.",
    "Class should include method demonstrating usage of overloaded methods.",
    "Usage method should create list initialized with specific type.",
    "Usage method should create two string variables initialized with specific values.",
    "Usage method should call first overloaded method with list and string variables.",
    "Usage method should create collection and call second overloaded method with collection and string variables.",
    "Code should illustrate method overloading based on parameter types.",
    "Extract code containing if statements.",
    "Extract code containing method calls.",
    "Extract code containing array creation.",
    "The extraction code contains a try-catch block.",
    "Extract code containing method calls.",
    "Code should define integer variable initialized with specific value.",
    "Code should define another integer variable initialized with different value.",
    "Code should define boolean variable storing result of logical expression.",
    "Logical expression uses comparison operator to evaluate relationship between two integer variables.",
    "Boolean variable stores negation of comparison result.",
    "The extraction code contains return statements.",
    "Extract code containing class declaration statement.",
    "Class has specific method serving as program entry point.",
    "Inside that method there is a single operation.",
    "Operation uses object's method to print fixed string to console.",
    "Submit code appears multiple times in context.",
    "Extract code containing method calls.",
    "Program should contain at least two classes.",
    "Source class UtilityClass should have static method.",
    "There should be nested static class within source class.",
    "Nested class should contain non-static method that calls one of static methods of source class.",
    "Extract code containing assignment statement.",
    "Extract code containing if statements.",
    "Extract code containing method calls.",
    "Extract code containing assignment statement.",
    "Extract code containing if statements.",
    "Extract code containing method calls.",
    "Program should contain at least two classes.",
    "Source class UtilityClass should have static method.",
    "There should be nested static class within source class.",
    "Nested class should contain non-static method that calls one of static methods of source class.",
    "Class should be defined as public class allowing access from other classes.",
    "Class should contain protected integer instance variable initialized to specific value.",
    "Class should include protected method returning integer.",
    "Method should return value of instance variable defined in class.",
    "Access modifiers ensure variable and method accessible by subclasses and same package classes.",
    "Class should be defined as public class allowing access from other classes.",
    "Class should contain method with no parameters and no return value.",
    "Method should define local integer variable initialized to specific value.",
    "Method should include conditional statement checking boolean expression.",
    "Method should print integer variable value if condition evaluates to true.",
    "Method should include else block also printing integer variable value if condition evaluates to false.",
    "Method should demonstrate conditional logic and console output.",
    "The extraction code contains a try-catch block.",
    "Extract code containing method calls.",
    "Extract code containing class declaration statement.",
    "Extract code containing method calls.",
    "Class should define multiple overloaded methods with same name but different parameter types.",
    "First method should accept a list and two strings as parameters.",
    "Second method should accept a collection and two strings as parameters.",
    "Methods should not return any value.",
    "Class should include method demonstrating usage of overloaded methods.",
    "Usage method should create list initialized with specific type.",
    "Usage method should create two string variables initialized with specific values.",
    "Usage method should call first overloaded method with list and string variables.",
    "Usage method should create collection and call second overloaded method with collection and string variables.",
    "Code should illustrate method overloading based on parameter types.",
    "Method should be defined as public method with no parameters and no return value.",
    "Method should declare local variable of specified type.",
    "Method should include try block initializing local variable with specific value.",
    "Method should include finally block executing after try block regardless of exception.",
    "Finally block should be present but contain no operations.",
    "Method should attempt to print local variable value after try and finally blocks.",
    "Code should demonstrate exception handling and variable scope.",
    "Class has specific method serving as program entry point.",
    "Inside that method there is a single operation.",
    "Operation uses object's method to print fixed string to console.",
    "There is a constructor defined for the class.",
    "Constructor contains two sets of conditional statements checking if input parameters are null.",
    "Based on null check results for each parameter, different assignment operations initialize instance variables of class.",
    "Extract code containing assignment statement.",
    "Extract code containing method calls.",
    "Code should be contained within public class defined in specified package.",
    "Class should include public method that does not accept any parameters and does not return a value.",
    "Method should declare multiple local string variables each initialized with specific string value.",
    "Method should concatenate all string variables into single output.",
    "Method should print concatenated string to console.",
    "Code should illustrate use of local variables and string manipulation.",
    "Class should define multiple overloaded methods with same name but different parameter types.",
    "First method should accept a list and two strings as parameters.",
    "Second method should accept a collection and two strings as parameters.",
    "Methods should not return any value.",
    "Class should include method demonstrating usage of overloaded methods.",
    "Usage method should create list initialized with specific type.",
    "Usage method should create two string variables initialized with specific values.",
    "Usage method should call first overloaded method with list and string variables.",
    "Usage method should create collection and call second overloaded method with collection and string variables.",
    "Code should illustrate method overloading based on parameter types.",
    "Method takes four parameters of different types including object of type Identity and three strings.",
    "There is no implementation body shown for method; unclear what operations performed with passed-in parameters.",
    "There is a constructor defined for the class.",
    "Constructor contains two sets of conditional statements checking if input parameters are null.",
    "Based on null check results for each parameter, different assignment operations initialize instance variables of class.",
    "Code should retrieve object from data access object based on specified title.",
    "Retrieved object should be assigned to a variable.",
    "Code should include conditional statement checking if retrieved object is null.",
    "If object is null, code should throw runtime exception.",
    "Exception message constructed to indicate no object found for specified title.",
    "Code should demonstrate error handling through exception throwing responding to null check.",
    "There is variable assignment operation where value retrieved from data access object's method call.",
    "Conditional statement follows to check if assigned variable is null.",
    "When variable null condition met, exception thrown with specific error message indicating entity not found based on title.",
    "There is a constructor defined for the class.",
    "Constructor contains two sets of conditional statements checking if input parameters are null.",
    "Based on null check results for each parameter, different assignment operations initialize instance variables of class.",
    "Code should be contained within public class defined in specified package.",
    "Class should include public method that does not accept any parameters and does not return a value.",
    "Method should declare multiple local string variables each initialized with specific string value.",
    "Method should concatenate all string variables into single output.",
    "Method should print concatenated string to console.",
    "Code should illustrate use of local variables and string manipulation.",
    "Class imports specific Java class.",
    "It defines private static final variable with fixed value.",
    "There is private method that throws an exception.",
    "Inside method are declarations of multiple arrays and two for loops performing different operations based on conditions and array element accesses.",
    "Class has private final variable declared.",
    "There is constructor defined in class.",
    "Inside constructor operations include creating instance of StringBuilder, performing multiple append operations on it, using it to assign value to private final variable, and printing StringBuilder instance.",
    "There is conditional statement checking certain condition related to an object.",
    "Inside conditional block are operations adding object to collection and performing insertion operation related to object using some data access mechanism inferred from dao.insert.",
    "Extracted part involves conditional check and subsequent operations carried out when condition met for handling relevant object.",
    "Foobar class imports java.math.BigDecimal class.",
    "It defines private static final variable MAX_LEVELS with value of 5.",
    "Class has private method init which throws an Exception.",
    "Extract code containing if statements.",
    "The extraction code contains continue statements.",
    "Extract code containing for statement.",
    "Extract code containing array creation.",
    "Code should define integer variable initialized to specific value.",
    "Code should print integer variable value to console.",
    "Transformation should create private method returning integer.",
    "Method should directly return specified integer value without using local variable.",
    "Transformation illustrates concise and efficient way returning constant value from method.",
    "Code contains series of conditional statements checking different conditions related to variables.",
    "There are operations for variable assignment and initialization within code block including creating instances of collections like ArrayList and HashMap.",
    "Extracted parts involve conditional checks leading to returning values or performing further operations such as modifying string variable and creating new variables and collections for holding data.",
    "Method should perform operations by invoking two other methods.",
    "First method call passes string representation of number as parameter.",
    "Second method call also passes string representation of same number as varargs parameter.",
    "Method should demonstrate use of method overloading based on parameter types.",
    "First invoked method accepts single string argument.",
    "Second invoked method accepts multiple string arguments allowing flexibility in number of parameters passed.",
    "Code should illustrate conversion of integer to string using built-in method.",
    "Class should contain method returning integer value.",
    "Method should declare and initialize two integer variables with specific values.",
    "Method should modify one integer variable based on value of other.",
    "Boolean variable should be declared and initialized to true value.",
    "Method should include conditional statement checking boolean variable.",
    "If condition is true, method should return value of second integer variable.",
    "If condition is false, method should assign value of second variable to first.",
    "Method should reassign new value to second integer variable.",
    "Final return statement should provide value of one integer variable demonstrating conditional logic and variable manipulation.",
    "Method should be private and accept multiple parameters including print stream, header string, array of integers, style string, and map.",
    "Method should print header and style to output stream formatted within curly braces.",
    "Method should iterate over collection of strings, creating new runnable for each string.",
    "Within runnable, method accesses index from integer array and prints formatted string combining current string and index.",
    "Method should demonstrate use of inner classes specifically anonymous inner classes implementing Runnable interface.",
    "Final output should be properly structured with closing brace printed after iteration completes.",
    "Code should illustrate use of lambda expressions or anonymous classes for concurrent or delayed execution though currently lacks invocation.",
    "Class SeparateInit defines two separate methods named context1 and context2.",
    "Both methods have same method body structure.",
    "In each method, integer variable v is declared and then assigned value 4.",
    "Extracted statements within method bodies are variable declaration and assignment expressions for integer variable v.",
    "Code should define integer variable initialized to specific value.",
    "Code should print integer variable value to console.",
    "Transformation should create private method returning integer.",
    "Method should directly return specified integer value without using local variable.",
    "Transformation illustrates concise and efficient way returning constant value from method.",
    "There is static block defined within class though surrounding class not fully shown.",
    "Static block contains single statement.",
    "Extracted statement is call to println method of System.out printing string \"HW\" to console.",
    "Method should be private and accept multiple parameters including print stream, header string, array of integers, style string, and map.",
    "Method should print header and style to output stream formatted within curly braces.",
    "Method should iterate over collection of strings, creating new runnable for each string.",
    "Within runnable, method accesses index from integer array and prints formatted string combining current string and index.",
    "Method should demonstrate use of inner classes specifically anonymous inner classes implementing Runnable interface.",
    "Final output should be properly structured with closing brace printed after iteration completes.",
    "Code should illustrate use of lambda expressions or anonymous classes for concurrent or delayed execution though currently lacks invocation.",
    "Method should be generic allowing type parameter specified when method called.",
    "Method should accept single parameter representing a class type.",
    "Method should print blank line to console.",
    "Method should return value of specified generic type although current implementation returns null.",
    "Method signature indicates handling various types enhancing flexibility and reusability.",
    "Method should demonstrate use of generics defining return types based on class type provided as argument.",
    "Method should handle variable number of string parameters.",
    "It should validate number of parameters allowing between three and five; if not, print help message and exit.",
    "Method should extract and process input and output methods from parameters normalizing them to lowercase.",
    "Depending on specified input method, print appropriate messages and extract additional parameters as needed.",
    "Method should handle multiple input options including console, CSV, and database sources.",
    "It should also handle various output methods including console, CSV, XML, and HTML.",
    "If unrecognized input or output method is provided, print error message indicating bad source.",
    "Code should demonstrate robust parameter handling and provide clear feedback based on input received.",
    "First code piece contains loop operation with callback function having multiple statements inside it.",
    "Second code piece defines function encapsulating same loop operation with identical callback structure as first one.",
    "Common part extracted is loop construct along with callback including multiple statements performing operations within loop.",
    "Class SeparateInit defines two separate methods named context1 and context2.",
    "Both methods have same method body structure.",
    "In each method, integer variable v is declared and then assigned value 4.",
    "Extracted statements within method bodies are variable declaration and assignment expressions for integer variable v.",
    "Class should define two separate methods each initializing local integer variable.",
    "Each method should declare variable before initialization demonstrating separate contexts.",
    "Variable should be assigned value of 4 in both methods illustrating similar logic.",
    "Both methods should not return any value or accept any parameters focusing solely on variable initialization.",
    "Methods should showcase independent scopes for variable v local to each method.",
    "Class should contain method demonstrating variable declaration.",
    "Method should declare String variable.",
    "String variable should be named but not initialized indicating potential issue.",
    "Method should have void return type meaning it does not return a value.",
    "Method's purpose is to illustrate variable scope within method context.",
    "There is static block defined within class though surrounding class not fully shown.",
    "Static block contains single statement.",
    "Extracted statement is call to println method of System.out printing string \"HW\" to console.",
    "Class StepOne defines single method named context3.",
    "Method context3 contains multiple statements related to string variable operations.",
    "Extracted statements involve declaring string variables s1 and s2 and performing assignment operations along with concatenation using += operator on those string variables.",
    "Class should contain method initializing two separate string variables.",
    "Each variable should be declared before initialization demonstrating independent contexts.",
    "First string variable assigned value \"aa\" then concatenated with \"postfix 1\".",
    "Second string variable also initialized with \"aa\" and concatenated with \"postfix 2\".",
    "Method should not return any value focusing solely on manipulation of string variables within its scope.",
    "Class should contain method performing no operations besides variable initialization.",
    "Method should declare integer variable.",
    "Integer variable initialized to zero.",
    "Method should have void return type indicating no value returned.",
    "Method's sole purpose is to demonstrate variable declaration and initialization within scope.",
    "Class should contain method demonstrating variable declaration.",
    "Method should declare String variable.",
    "String variable should be named but not initialized indicating potential issue.",
    "Method should have void return type meaning it does not return a value.",
    "Method's purpose is to illustrate variable scope within method context.",
    "Method should declare variable of type long.",
    "Long variable initialized with value of 0L.",
    "Method should perform decrement operation on long variable.",
    "Method should further modify long variable by subtracting integer value.",
    "Purpose of method is to demonstrate operations on long data type.",
    "Method should declare two integer variables with initial values of 1 and 2.",
    "Method should utilize formatting class to create formatted output strings.",
    "Method should print value of first integer using specified format.",
    "Method should print value of second integer using specified format.",
    "Purpose of method is to demonstrate formatted output for integer values.",
    "Class should contain method demonstrating variable declaration.",
    "Method should declare String variable.",
    "String variable should be named but not initialized indicating potential issue.",
    "Method should have void return type meaning it does not return a value.",
    "Method's purpose is to illustrate variable scope within method context.",
    "Class should contain method performing no operations besides variable initialization.",
    "Method should declare integer variable.",
    "Integer variable initialized to zero.",
    "Method should have void return type indicating no value returned.",
    "Method's sole purpose is to demonstrate variable declaration and initialization within scope.",
    "Extract code containing if statements.",
    "This condition is relatively complex, involving multiple logical checks and nested conditions.",
    "The use of logical operators (&&, ||) enables nuanced control over which conditions must be satisfied.",
    "The condition uses short-circuit evaluation, meaning once a condition fails.",
    "Extract code containing if statements.",
    "Extract code containing for statement.",
    "Extract code containing class declaration statement.",
    "Extract code containing method calls.",
    "Code snippet contains three separate variable declarations.",
    "All variable declarations are of final type and are used to initialize different variables related to image processing inferred from variable names.",
    "Extracted statements are all assignment expressions where values are assigned to newly declared final variables.",
    "Code contains two separate methods.",
    "Both methods are declared as generic methods with same type parameter placeholder.",
    "Each method has its own distinct method body with different statements inside them.",
    "An array of integers is declared and initialized to hold pixel data for an image part based on its width and height.",
    "A method is called to extract RGB data from specified image part resulting in another integer array.",
    "Two final integer variables defined to represent maximum starting coordinates X and Y for placing image part within larger image, calculated by subtracting image part dimensions from dimensions of main image.",
    "Code prepares data structures necessary for image manipulation or processing.",
    "Variables are declared as final indicating values cannot be reassigned after initialization.",
    "Extract code containing if statements.",
    "The extraction code contains return statements.",
    "Extract code containing if statements.",
    "Extract code containing for statement.",
    "Extract code containing class declaration statement.",
    "Extract code containing method calls.",
    "Class implements generic interface indicating it can be used for comparison operations.",
    "Method defined to provide mechanism for comparing two objects although it currently returns constant value.",
    "Method lacks specific logic for meaningful comparison suggesting it needs implementation to fulfill intended purpose.",
    "Absence of type parameters in interface implementation could lead to unchecked warnings during compilation.",
    "Extract code containing if statements.",
    "Extract code containing for statement.",
    "Extract code containing throw statement.",
    "Extract code in lambda expressions.",
    "Extract code containing if statements.",
    "Extract code containing for statement.",
    "Extract code containing throw statement.",
    "Extract code in lambda expressions.",
    "Extract code containing for statement.",
    "New object of class such as JSONObject is instantiated.",
    "Method toString() is called on object to convert it to string representation.",
    "Object is printed to console.",
    "For loop is used to iterate over range based on property or method of object.",
    "Loop's range or iteration condition is based on attribute or method call of created object though specific attribute or method not specified.",
    "Extract code containing if statements.",
    "Extract code containing for statement.",
    "Extract code containing throw statement.",
    "Extract code in lambda expressions.",
    "Extract code containing if statements.",
    "Extract code containing for statement.",
    "Extract code containing throw statement.",
    "Extract code in lambda expressions.",
    "Extract code containing if statements.",
    "The extraction code contains for statement.",
    "Extract code containing array creation.",
    "Extract code containing method calls.",
    "The extraction code contains return statements.",
    "Extract code containing if statements.",
    "Extract code containing for statement.",
    "The extraction code contains return statements.",
    "Extract code containing if statements.",
    "Extract code containing for statement.",
    "The extraction code contains return statements.",
    "Extract code containing if statements.",
    "Extract code containing for statement.",
    "Extract code in lambda expressions.",
    "Extract code containing if statements.",
    "Extract code containing for statement.",
    "Extract code containing throw statements.",
    "Extract code containing class declaration statement.",
    "Extract code containing inner class.",
    "Method is intended to manage specific feature based on input condition with option to enable or disable that feature.",
    "It starts by checking if input is null; if null method exits early indicating no further action necessary.",
    "Method ensures only one instance can be affected at a time by invoking separate method to clear previous settings before applying new ones.",
    "Based on input condition it decides whether to activate or deactivate feature demonstrating conditional control flow.",
    "Code attempts to execute division operation resulting in arithmetic error due to division by zero.",
    "It is wrapped in try-catch block allowing graceful handling of runtime exceptions.",
    "When exception occurs catch block captures RuntimeException and executes method to print stack trace providing insight into error origin.",
    "Structure illustrates use of exception handling to manage potential errors in program execution.",
    "Method is intended to manage specific feature based on input condition with option to enable or disable that feature.",
    "Extract code containing method calls.",
    "Code attempts to retrieve value from cache using method generating key based on input parameters.",
    "It is enclosed in try-catch block to handle potential exceptions arising during cache access.",
    "If throwable is caught code checks if it is instance of specific exception types related to execution errors.",
    "Depending on type of exception it retrieves underlying cause and rethrows it using utility method designed for unchecked exceptions preserving relevant error information.",
    "Two separate methods are defined in class.",
    "Both methods create anonymous Runnable class.",
    "Each Runnable defines run method performing specific action printing different messages.",
    "Both methods invoke run method of Runnable instance directly within method body.",
    "Methods contain identical structural patterns differing only in message printed within run method.",
    "Code initializes mutable list using utility method for creating empty list.",
    "Variable x defined as extension property intended for use with another class or type.",
    "Comment indicates additional code or context above snippet not included.",
    "println(size) statement likely intends to print size of list though unclear whether size refers to x.size() or another context.",
    "Code demonstrates basic list manipulation in language supporting extension properties and mutable collections.",
    "First line performs simple arithmetic operation adding two integer literals and assigning result to variable.",
    "Second line calculates product multiplying numeric constant by value of previously assigned variable.",
    "Code demonstrates basic variable assignment and arithmetic operations showcasing expressions in assignment context.",
    "Two separate methods are defined in class.",
    "Both methods create anonymous Runnable class.",
    "Each Runnable defines run method performing specific action printing different messages.",
    "Both methods invoke run method of Runnable instance directly within method body.",
    "Methods contain identical structural patterns differing only in message printed within run method.",
    "Two methods are defined in class.",
    "Both methods take same parameters.",
    "Both methods return result of calling same helper method with one of parameters as argument.",
    "Helper method defined separately and called in both methods.",
    "Structural pattern of methods identical with both simply passing one parameter to helper method and returning its result.",
    "Two variables are defined.",
    "Both variables assigned result of arithmetic expression.",
    "Each expression involves addition and division operation.",
    "Division operation performed first due to operator precedence.",
    "Expressions follow same structural pattern with different values.",
    "Method is called with boolean argument passing result to string builder.",
    "Method returns string created from string builder.",
    "String builder appends string conditionally based on boolean argument.",
    "Method uses string builder to construct string before returning it.",
    "Method's functionality encapsulated into single conditional append operation.",
    "Variable is initialized with value.",
    "Value of variable is printed to console.",
    "Code involves basic variable assignment followed by print operation.",
    "Output of print operation directly reflects variable's value.",
    "Method is called with boolean argument passing result to string builder.",
    "Method returns string created from string builder.",
    "Submit code appears multiple times in context.",
    "Class defines enumeration type.",
    "Enum implements Serializable interface.",
    "Two methods defined within enum.",
    "Methods contain identical logic but different return types: one returns Serializable type, other returns enum value.",
    "Both methods use if-else structure to determine which enum constant to return based on input value.",
    "Methods demonstrate redundant functionality with similar behavior.",
    "Class defines member variable foo and method bar.",
    "Method foo is overloaded: one version is instance method with variable argument int... args, other is member variable.",
    "Method bar attempts to pass member variable foo as argument to method foo causing ambiguity due to same name for variable and method.",
    "Variable foo is integer while method foo accepts variable argument list of integers int... args.",
    "Ambiguity between variable and method name leads to confusion or errors during code execution or compilation.",
    "Variable is initialized with null value.",
    "Conditional expression used to determine value of variable.",
    "If condition is true variable assigned one value.",
    "If condition is false variable assigned different value.",
    "Final value of variable determined by outcome of conditional expression.",
    "Variable assigned values within control flow structure based on boolean condition.",
    "Code defines variable foo and initializes it with null.",
    "Value of foo conditionally assigned based on boolean expression bar.",
    "If bar evaluates to true foo assigned string \"bar\".",
    "If bar evaluates to false foo assigned string \"foo\".",
    "Extract code containing if statement.",
    "The extraction code contains return statements.",
    "Extract code containing for statement.",
    "Extract code containing break statement.",
    "Extract code containing assignment statement.",
    "Class serves as main entry point for program containing public static method.",
    "Array of strings initialized with single element representing numeric value.",
    "Integer type variable declared and initialized by parsing first element of string array.",
    "Parsing method converts string representation of number into integer equivalent.",
    "First line performs simple arithmetic operation adding two integer literals and assigning result to variable.",
    "Extract code containing break statement.",
    "Method involves reading data from file and storing values into collection.",
    "Method handles potential exceptions specifically related to file handling and input/output operations.",
    "Variable initialized and its value printed at end of method but it is not modified during method's execution.",
    "Flow of execution includes multiple blocks where exceptions are caught and handled ensuring program does not terminate unexpectedly.",
    "Class contains method with no parameters and no return value named to indicate its purpose.",
    "Nested class defined within outer class containing its own method.",
    "Nested method calls outer class's method demonstrating access to enclosing context.",
    "There is print statement outputting empty line indicating placeholder for future content or formatting.",
    "Extract code containing assignment statement.",
    "Class serves as main entry point for program containing public static method.",
    "Array of strings initialized with single element representing numeric value.",
    "Class contains private method that does not return a value.",
    "Within method synchronized block used to control access to critical section ensuring thread safety.",
    "Synchronized block encompasses code meant to be executed in thread-safe manner.",
    "There are comments indicating start and end of code selection likely for clarity or future modifications.",
    "After synchronized block there is placeholder comment indicating presence of additional code unrelated to critical section.",
    "Method returns value of type String.",
    "Method uses selection to indicate specific section of code for extraction or modification.",
    "Within selection ThreadLocalRandom instance accessed to generate random value.",
    "toString() method called on random value converting it to string representation.",
    "Method has no parameters and likely intended to perform simple operation related to generating random string.",
    "Multi-way selection statement contains branch control structure.",
    "Specific branches of multi-way selection embed conditional logic.",
    "Execution of conditional branch ensures flow control through exit statement.",
    "Boolean variables used to track state changes and updated in conditional logic.",
    "Conditional judgment depends on time value of external system and may not meet specific trigger condition.",
    "Output statement records execution of logic branch.",
    "Final value of state variable displayed after logic executed.",
    "Class defines private method with void return type.",
    "Inside method synchronized block employed to manage concurrent access ensuring critical section executed safely by one thread at a time.",
    "Synchronized block encapsulates code intended to be run in thread-safe environment.",
    "Comments present to mark beginning and end of code selection likely for better readability or future code changes.",
    "Following synchronized block there is placeholder comment suggesting existence of subsequent code unrelated to synchronized context."
    ]
GENERATE_TOTAL = 1
refactor_name = "extract method"
OUTPUT_JAVA_DIR = "./gen_java_output"

prompt_results = batch_generate_prompts(
    total_generate=GENERATE_TOTAL,
    refactoring_type=refactor_name,
    feature_pool=extract_method_features,
    max_feature=6
)

fieldnames = [
    "sample_id",
    "refactoring_type",
    "pick_feature_count",
    "source_class",
    "target_class",
    "picked_features",
    "full_prompt"
]

with open("extract_method_prompt_output.csv", "w", encoding="utf-8-sig", newline="") as f:
    writer = csv.DictWriter(f, fieldnames=fieldnames)
    writer.writeheader()
    for row in prompt_results:
        csv_row = {
            "sample_id": row["sample_id"],
            "refactoring_type": row["refactoring_type"],
            "pick_feature_count": row["pick_feature_count"],
            "source_class": row["source_class"],
            "target_class": row["target_class"],
            "picked_features": "; ".join(row["picked_features"]),
            "full_prompt": row["full_prompt"]
        }
        writer.writerow(csv_row)

print("🎉 CSV prompt 文件生成完成：extract_method_prompt_output.csv")